// Lis fraz
const listeMots = [
  'chat',
  'chien',
  'maison',
  'soleil',
  'forêt',
  'ordinateur',
  'programmation',
  'plage',
  'aventure',
  'montagne',
  'pomme',
  'orange',
  'elephant',
  'musique',
  'jardin',
  'etoile',
  'pizza',
  'football',
  'voyage',
  'livre',
  'courage',
  'pluie',
  'arc-en-ciel',
  'voiture',
  'velo',
  'bougie',
  'reseau',
  'cafe',
  'famille',
  'liberte',
  'energie',
  'fleur',
  'sourire',
  'reve',
  'ocean',
  'oiseau',
  'parapluie',
  'piano',
  'train',
  'meteo',
  'papillon',
  'tigre',
  'panda',
  'robot',
  'miracle',
  'fantaisie',
  'abeille',
  'coccinelle',
  'arbre',
  'epice',
  'cascade',
  'bienveillance',
  'savoir',
  'illusion',
  'parfum',
  'mystere',
  'harmonie',
  'poesie',
  'vision',
  'cristal',
  'jubilation',
  'equilibre',
  'lumiere',
  'frisson',
  'echo',
  'eclat',
  'clarte',
  'tranquillite',
  'energie',
  'chaleur',
  'revelation',
  'serenite',
  'sagesse',
  'purete',
  'plenitude',
  'espoir',
  'emotion',
  'essence',
  'generosite',
  'illumination',
  'inspiration',
  'lueur',
  'magnificence',
  'emerveillement',
  'felicite',
  'rayonnement',
  'splendeur',
  'verite',
  'joie',
  'beaute',
  'paix',
  'eternite',
  'transcendance',
  'union',
  'feerie',
  'transe',
  'extase',
  'presence',
  'feminite',
  'masculinite',
  'souffle',
  'effervescence',
  'liberation',
  'evasion',
  'horizon',
  'evolution',
  'compassion',
  'cosmos',
  'insouciance',
  'vitalite',
  'resilience',
  'serendipite',
  'ludique',
  'incandescence',
];

// Lis fraz
const listePhrases = [
  "La vie est belle.",
  "Soyez heureux.",
  "Creez chaque jour.",
  "Soyez gentil.",
  "Apprenez de l'echec.",
  "Soyez curieux.",
  "Vivez l'instant present.",
  "Souriez toujours.",
  "Aimez ce que vous faites.",
  "Ayez confiance en vous.",
  "Soyez different.",
  "Soyez courageux.",
  "Soyez positif.",
  "Creez votre avenir.",
  "Soyez patient.",
  "Aimez avec le cœur.",
  "Continuez d'essayer.",
  "Ecoutez la sagesse.",
  "Revez grand.",
  "Soyez reconnaissant.",
];
